apiVersion: v1
kind: Service
metadata:
  name: astrovox-inference
  namespace: astrovox
  labels:
    app: astrovox-inference
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    app: astrovox-inference
