#!/bin/bash
echo "=== AstrovoxAI Deployment ==="
echo ""
echo "1. Push code to GitHub:"
echo "   git push origin main"
echo ""
echo "2. Go to https://dashboard.render.com/blueprint/new"
echo "3. Connect repo: paudelprabeeyeesh-cmd/AstrovoxAi"
echo "4. Render will detect render.yaml automatically"
echo "5. Add env var OPENAI_API_KEY in Render dashboard"
echo "6. Click Create"
echo ""
echo "After deploy, verify:"
echo "   curl https://astrovox-api.onrender.com/health"
echo "   curl https://astrovox-api.onrender.com/metrics"
