apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-replica-config
  namespace: read-replicas
data:
  postgresql.conf: |
    hot_standby = on
    wal_level = replica
    max_wal_senders = 10
    wal_keep_size = 1GB
    hot_standby_feedback = on
    random_page_cost = 1.1
    effective_cache_size = 2GB
    shared_buffers = 512MB
    work_mem = 64MB
    maintenance_work_mem = 128MB
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-replica-secret
  namespace: read-replicas
type: Opaque
stringData:
  password: astrovox_pass
