apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "astrovox.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astrovox.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "astrovox.selectorLabels" . | nindent 6 }}
