apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astrovox.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astrovox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
