{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astrovox.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astrovox.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
