apiVersion: v1
kind: Service
metadata:
  name: {{ include "astrovox.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astrovox.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "astrovox.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  type: {{ .Values.service.type }}
