apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kong.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: "change-me-in-production"
  admin-token: "change-me-in-production"
