apiVersion: v1
kind: ConfigMap
metadata:
  name: astrovox-config
  namespace: astrovox
data:
  APP_ENV: production
  LOG_LEVEL: info
  REDIS_URL: redis://redis-master:6379/0
  DATABASE_URL: postgresql://astrovox:astrovox_pass@postgres:5432/astrovox
  JAEGER_URL: http://jaeger:14268/api/traces
