apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astrovox
  namespace: astrovox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - astrovox.ai
      secretName: astrovox-tls
  rules:
    - host: astrovox.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: astrovox
                port:
                  number: 80
