from .audio import router as audio_router
from .voice import router as voice_router
from .files import router as files_router
from .embeddings import router as embeddings_router
from .structured import router as structured_router
from .workflows import router as workflows_router
from .projects import router as projects_router
from .templates import router as templates_router
from .research import router as research_router
from .artifacts import router as artifacts_router
from .batch import router as batch_router
from .conversation_branching import router as conversation_branching_router
from .context_extension import router as context_extension_router
from .code_agent import router as code_agent_router
from .rag import router as rag_router
from .rag_pipeline import router as rag_pipeline_router
from .memory import router as memory_router
from .memory_management import router as memory_management_router
from .memory_controls import router as memory_controls_router
from .models_api import router as models_api_router
from .neural_bci import router as neural_bci_router
from .multi_agent import router as multi_agent_router
from .moe_load_balancing import router as moe_load_balancing_router
from .model_distillation import router as model_distillation_router
from .paged_attention import router as paged_attention_router
from .speculative_decoding import router as speculative_decoding_router
from .admin_api import router as admin_api_router
from .safety_api import router as safety_api_router
from .skills import router as skills_router
from .plugin_marketplace import router as plugin_marketplace_router
from .analytics_api import router as analytics_api_router
from .images import router as images_router
from .finetuning import router as finetuning_router
from .audio_outputs import router as audio_outputs_router
from .knowledge_graph_api import router as knowledge_graph_api_router
from .inference_engine_api import router as inference_engine_api_router
from .agi_router import router as agi_router
from .integrations import router as integrations_router
from .mcp import router as mcp_router
