{{- if .Values.auth.sentinel }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  sentinel-password: {{ .Values.auth.sentinelPassword | b64enc | quote }}
{{- end }}
