apiVersion: v1
kind: Service
metadata:
  name: astrovox-backend
  namespace: astrovox
  labels:
    app: astrovox-backend
spec:
  selector:
    app: astrovox-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: astrovox-frontend
  namespace: astrovox
  labels:
    app: astrovox-frontend
spec:
  selector:
    app: astrovox-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  type: ClusterIP
