server:
  address: ":4040"

auth:
  no_auth: true

storage:
  path: /var/lib/pyroscope

profiles:
  - path: /tmp/profiles
    application-name: astrovox
    spy-name: default
    sample-rate: 100
    format: pprof
