apiVersion: v2
name: astrovox-postgresql
description: PostgreSQL subchart for AstrovoxAI
type: application
version: 0.1.0
appVersion: "16.2"
keywords:
  - postgresql
  - database
  - astrovoxai
maintainers:
  - name: AstrovoxAi Team
    email: dev@astrovoxai.com
