
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astrovox-backend
spec:
  ingressClassName: nginx
  rules:
  - host: api.astrovox.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: astrovox-backend
            port:
              number: 80
