apiVersion: v1
kind: Secret
metadata:
  name: astrovox-backend-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2FzdHJvdm94OmFzdHJvdm94X3Bhc3NAcG9zdGdyZXM6NTQzMi9hc3Ryb3ZveA==
  NEO4J_PASSWORD: bmVvNGpfcGFzc3dvcmQ=
