"""Automatic differentiation: dynamic graph, reverse-mode engine, and utilities."""

from astrovox.autograd.backward import AddBackward, MulBackward, grad_for_shape
from astrovox.autograd.engine import (
    BackwardResult,
    Engine,
    backward,
    clip_grad_norm,
    full_like,
    grad_norm,
    ones_like,
    zeros_like,
)
from astrovox.autograd.function import Function, GraphNode, Node
from astrovox.autograd.gradients import (
    GradientCheckResult,
    check_gradients,
    flatten_gradients,
    gradcheck,
    gradient_map,
    has_gradients,
    numerical_gradient,
    zero_grad,
    zero_grad_module,
)
from astrovox.autograd.graph import (
    GraphContext,
    current_graph,
    enable_grad,
    free_graph,
    graph_size,
    is_grad_enabled,
    no_grad,
    topological_order,
    walk_from,
)

__all__ = [
    "AddBackward",
    "BackwardResult",
    "Engine",
    "Function",
    "GradientCheckResult",
    "GraphContext",
    "GraphNode",
    "MulBackward",
    "Node",
    "backward",
    "check_gradients",
    "clip_grad_norm",
    "current_graph",
    "enable_grad",
    "flatten_gradients",
    "free_graph",
    "full_like",
    "grad_for_shape",
    "grad_norm",
    "gradcheck",
    "gradient_map",
    "graph_size",
    "has_gradients",
    "is_grad_enabled",
    "no_grad",
    "numerical_gradient",
    "ones_like",
    "topological_order",
    "walk_from",
    "zero_grad",
    "zero_grad_module",
    "zeros_like",
]
