apiVersion: v2
name: astrovox
description: A Helm chart for Astrovox AI
version: 0.1.0
appVersion: "2.0.0"
keywords:
  - ai
  - chatbot
  - fastapi
  - react
maintainers:
  - name: AstrovoxAI Team
    email: team@astrovox.ai
