"""Debugging tools for the autograd engine and tensor graph."""

from astrovox.debug.diagnostics import (
    Dashboard,
    Distribution,
    MemoryReport,
    ParameterGradientCheck,
    UpdateStatus,
    dashboard,
    format_consistency,
    format_distribution,
    format_memory,
    format_updates,
    gradient_consistency,
    gradient_distribution,
    memory_report,
    propagation_depth,
    propagation_trace,
    validate_backward,
    validate_shapes,
    verify_updates,
)
from astrovox.debug.inspector import (
    GraphReport,
    NodeInfo,
    check_graph,
    describe_tensor,
    find_constant_subgraphs,
    format_gradient_table,
    gradient_table,
    inspect,
)

__all__ = [
    "Dashboard",
    "Distribution",
    "GraphReport",
    "MemoryReport",
    "NodeInfo",
    "ParameterGradientCheck",
    "UpdateStatus",
    "check_graph",
    "dashboard",
    "describe_tensor",
    "find_constant_subgraphs",
    "format_consistency",
    "format_distribution",
    "format_gradient_table",
    "format_memory",
    "format_updates",
    "gradient_consistency",
    "gradient_distribution",
    "gradient_table",
    "inspect",
    "memory_report",
    "propagation_depth",
    "propagation_trace",
    "validate_backward",
    "validate_shapes",
    "verify_updates",
]
