apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
